// react/Fluid.jsx
import { useRef, useState, useEffect } from 'react'
import { getContentStyle, getContentWidth } from '../common/utils'

export default function ({ base, children }) {
  const bases = Array.isArray(base) ? base : [base]

  const [contentWidth, setContentWidth] = useState(bases[0])
  const [contentScale, setContentScale] = useState(1)
  const containerRef = useRef(null)

  const contentStyle = getContentStyle(contentWidth, contentScale)

  useEffect(() => {
    const resizeObserver = new ResizeObserver(() => {
      const containerWidth = containerRef.current.offsetWidth
      const contentWidth = getContentWidth(bases, containerWidth)

      setContentWidth(contentWidth)
      setContentScale(containerWidth / contentWidth)
    })

    if (containerRef.current) {
      resizeObserver.observe(containerRef.current)
    }

    return () => {
      if (containerRef.current) {
        resizeObserver.unobserve(containerRef.current)
      }
    }
  }, [base])

  return (
    <div ref={containerRef}>
      <div style={contentStyle}>{children}</div>
    </div>
  )
}

// vue2/Fluid.vue
<template>
  <div ref="container">
    <div :style="contentStyle">
      <slot></slot>
    </div>
  </div>
</template>

<script>
import { getContentStyle, getContentWidth } from '../common/utils'

export default {
  props: {
    base: {
      type: [Number, Array],
      required: true,
    },
  },
  data() {
    const bases = Array.isArray(this.base) ? this.base : [this.base]

    return {
      bases,
      contentWidth: bases[0],
      contentScale: 1,
    }
  },
  computed: {
    contentStyle() {
      return getContentStyle(this.contentWidth, this.contentScale)
    },
  },
  mounted() {
    this.resizeObserver = new ResizeObserver(() => {
      const containerWidth = this.$refs.container.offsetWidth
      this.contentWidth = getContentWidth(this.bases, containerWidth)
      this.contentScale = containerWidth / this.contentWidth
    })

    this.resizeObserver.observe(this.$refs.container)
  },
  beforeDestroy() {
    this.resizeObserver.unobserve(this.$refs.container)
  },
}
</script>
